- title: Drag and Drop!
  photo: drag
  buttons:
    - text: Guide
      href: https://dreamtime.tech/docs/guide/upload
  summary: |-
    No matter where you are, you can always drag and drop your photos and folders.
  content: |-
    No matter where you are, you can always drag and drop your photos, folders and even photos from your web browser. Avoid having to return to the upload page every time.

- title: What are the best photos?
  photo: tips
  buttons:
    - text: More information
      href: https://dreamtime.tech/docs/guide/photos
  summary: |-
    Not all photos provide good results, click here to know the characteristics of a good photo.
  content: |-
    - Only one person in the photo.
    - Less clothing as possible. Bikinis work better.
    - Body facing the camera.
    - Person standing in a straight position without crossing arms or legs.
    - Body visible and unobstructed.

- title: Settings.
  photo: settings
  buttons:
    - text: Go to settings
      href: /settings
  summary: |-
    Customize the behavior of DreamTime and make it a professional application to create fake nudes.
  content: |-
    Customize the behavior of DreamTime and make it a professional application to create fake nudes.

    - Optimize application and algorithm performance.
    - Change the behavior of the photo upload or the location of the queue bar.
    - Set nudification alerts.
    - Change the folder where the photos or algorithms are located.
    - More!

- title: Photo preferences.
  photo: preferences
  buttons:
    - text: Go to photo preferences
      href: /settings/preferences
  summary: |-
    Create the nude of your dreams by customizing the body, using algorithms to improve the result and more!
  content: |-
    Photo preferences allow you to customize the result and create the nude of your dreams:

    - Change the size of the body parts to your liking.
    - Use different scale methods or additional algorithms to improve the result.
    - Set additional photo runs with random or increased preferences.
    - More!

- title: Get better results.
  photo: better-results
  buttons:
    - text: Go to preferences
      href: /settings
  summary: |-
    Is your photo not giving good results? Changing and experimenting with the photo preferences can help a lot.
  content: |-
    Is your photo not giving good results? Changing and experimenting with the photo preferences can help a lot:

    - **Scale method:** The `Crop` and `Overlay` options usually give the best results.
    - **Crop position:** If you are using `Crop`, `Overlay` or `Color Padding` the position of the crop tool can be the key to a good result, even moving it a few pixels can make a difference.

    And remember the photos that work best:

    - Only one person in the photo.
    - Less clothing as possible. Bikinis work better.
    - Body facing the camera.
    - Person standing in a straight position without crossing arms or legs.
    - Body visible and unobstructed.


- title: Preferences Mode.
  photo: preferences-mode
  buttons:
    - text: Go to settings
      href: /settings
  summary: |-
    Too many options? Or few? Adapt it to your style.
  content: |-
    Preferences mode allows you to increase or decrease the number of options depending on your style or experience using the application.

    - **Minimal**: Only the body preferences are shown, all other options will be set to make the process as automatic as possible.
    - **Simple**: Same as Minimal but you can change the `Scale method`.
    - **Normal**: All options available, this is the original DreamTime experience.
    - **Custom masks**: Advanced mode that requires experience and time. In this mode you will work with the masks generated by the algorithm making manual modifications to each one of them, this allows to drastically improve the quality of the fake nude if it is done correctly.
      - The `Nudify` or `Start` buttons are disabled for the photo since the masks must be generated one by one.
      - The `Per run` preferences are disabled.

- title: Custom masks.
  photo: masks
  buttons:
    - text: Guide
      href: https://dreamtime.tech/docs/guide/custom-masks
  summary: |-
    The custom masks allows you to obtain results that only a human could create!
  content: |-
    With the custom masks mode you can work with the masks generated by the algorithm and obtain results that DreamPower alone is not capable of.

    Visit the guide to get all the information and tips necessary to start using this mode!

- title: Tips? Ads? You decide.
  photo: tips-ads
  buttons:
    - text: Go to settings
      href: /settings
    - text: Report ad
      href: https://dreamtime.tech/docs/support/feedback#others
  summary: |-
    Now you can find help tips and ads in this space. You can enable or disable this behavior in the settings.
  content: |-
    In this version of DreamTime you can find help tips and/or ads in the bottom part of the menu.

    You can enable or disable this behavior in the settings.

- title: Video nudification.
  photo: videos
  summary: |-
    Don't just stay with static photos, you can also nudify gifs, webm and mp4 videos!
  content: |-
    With DreamTime you can nudify gifs, webm and mp4 videos, from the Internet or by uploading the files to the application.

    **Be sure to use short duration videos, otherwise prepare to meet the memory eating beast.**

- title: Technical support.
  photo: support
  buttons:
    - text: Go to chat
      href: https://chat.dreamnet.tech
    - text: More contact options
      href: https://dreamtime.tech/docs/support/feedback
  summary: |-
    Something not working? Have you found a bug? Use our chat or communicate with a developer easily.
  content: |-
    Whether you have a problem or just want to talk to other people who use the application, our contact channels are available to everyone.
