- id: user
  label: User ID.
  description: Anonymous identification for your session.
  input: input

- id: app.disableHardwareAcceleration
  label: Hardware acceleration.
  description: Can improve performance on some devices.<br>* Requires restart to take effect.
  tooltip: Use your GPU to speed up the application performance. (Not the nudification algorithm)
  input: select
  options:
    - label: Disabled
      value: true
    - label: Enabled
      value: false

- id: app.uploadMode
  label: Upload mode.
  description: The uploaded photos will be added to the selected section.
  tooltip: |-
    - **Pending:** The photos will keep waiting to be configured and nudified.
    - **Pending -> Preferences:** When uploading a photo it will be placed in `Pending` and then you will be transferred to the preferences of the photo, in case of uploading multiple photos you will be transferred to the preferences of the last photo.
    - **Queue:** The uploaded photos will be placed in the queue where they will be nudified as soon as possible.
  input: select
  options:
    - label: Pending
      value: none
    - label: Pending -> Preferences
      value: go-preferences
    - label: Queue
      value: add-queue

- id: app.duplicates
  label: Allow duplicates.
  description: Allow the upload of the same photo multiple times.
  tooltip: |-
    With this you can upload a photo multiple times and set different preferences or crop areas without having to wait, this will also make the photos show a unique identification to be able to differentiate.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: app.queuePosition
  label: Queue position.
  description: Change the position of the queue bar.
  input: select
  options:
    - label: Right
      value: right
    - label: Left
      value: left

- id: app.showAds
  label: Show Ads.
  description: Show ads at the bottom of the menu.
  tooltip: Allowing ads helps DreamTime development. These ads are selected by DreamNet.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: app.showTips
  label: Show Tips.
  description: Show help tips at the bottom of the menu.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: preferences.advanced.device
  label: Device.
  description: GPU is faster but depends on the device VRAM. CPU is slower but uses system RAM.
  tooltip: |-
    Nudification times:
    ---

    - **NVIDIA GPU:** Between 5 and 60 seconds.
    - **CPU:** Between 1 and 15 minutes.
  input: select
  options:
    - label: CPU
      value: CPU
    - label: NVIDIA GPU
      value: GPU

- id: processing.gpus
  label: GPU.
  description: Graphics card to use.

- id: processing.cores
  label: CPU Cores.
  description: "Using more cores increases the nudification speed for GIFs and videos but decrease system stability.<br>Recommended: 1"
  input: input

- id: processing.usePython
  label: Use Python.
  description: Use Python to start the nudification algorithm. Enable this only if you know what are you doing.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: preferences.mode
  label: Preferences Mode.
  description: Complexity of options.
  tooltip: |-
    - **Minimal**: Only the body preferences are shown, all other options will be set to make the process as automatic as possible.
    - **Simple**: Same as Minimal but you can change the `Scale method`.
    - **Normal**: All options available, this is the original DreamTime experience.
    - **Custom masks**: Advanced mode that requires experience and time. In this mode you will work with the masks generated by the algorithm making manual modifications to each one of them, this allows to drastically improve the quality of the fake nude if it is done correctly.
      - The `Nudify` or `Start` buttons are disabled for the photo since the masks must be generated one by one.
      - The `Per run` preferences are disabled.
  input: select
  options:
    - label: Minimal
      value: 0
    - label: Simple
      value: 1
    - label: Normal
      value: 2
    - label: Custom masks
      value: 3
  animated-options:
    - label: Minimal
      value: 0
    - label: Simple
      value: 1
    - label: Normal
      value: 2

- id: preferences.advanced.scaleMode
  label: Scale method.
  description: Indicates how the photo will be scaled to a size compatible with the algorithm.
  tooltip: |-
    - **None:** The algorithm will be forced to process the photo using an approximation of its original size. Please note that this option can considerably increase memory consumption and return worse results.
    - **Automatic Resize:** The algorithm will resize the photo without maintaining the aspect ratio.
    - **Automatic Padding:** The algorithm will resize the photo while maintaining the aspect ratio.
    - **Automatic Crop:** The algorithm will crop the photo while maintaining the aspect ratio.
    - **Overlay:** Allows you to select which area of the photo you want to crop, nudify and then restore to the original photo. This tool makes the photos keep their original size.
    - **Crop:** Allows you to crop the photo manually. (Like in DeepNude)
    - **Color padding:**  This method tricks the algorithm into avoiding the color change that occurs during nudification but sacrificing photo and fake nude quality.
  input: select
  options:
    - label: None
      value: none
    - label: "Automatic Resize"
      value: auto-rescale
    - label: "Automatic Padding"
      value: auto-resize
    - label: "Automatic Crop"
      value: auto-resize-crop
    - label: Overlay
      value: overlay
    - label: Crop
      value: cropjs
    - label: Color Padding
      value: padding
  animated-options:
    - label: None
      value: none
    - label: "Automatic Resize"
      value: auto-rescale
    - label: "Automatic Padding"
      value: auto-resize
    - label: "Automatic Crop"
      value: auto-resize-crop

- id: preferences.body.runs.mode
  label: Mode.
  description: How the body preferences will be changed in each run.
  tooltip: |-
    - **Randomize:** Each run will have random body preferences.
    - **Increase by Step:** Each run will increase the body preferences by the specified step.
  input: select
  options:
    - label: Disabled
      value: false
    - label: Randomize
      value: randomize
    - label: Increase by Step
      value: increase

- id: preferences.body.runs.count
  label: Count.
  description: Number of times the photo will be nudified.
  input: input
  attrs:
    type: number
    min: 2

- id: preferences.body.runs.rate
  label: Step.
  input: input
  attrs:
    type: number
    min: 0.1
    step: 0.1
    max: 2

- id: preferences.advanced.useColorPaddingStrip
  label: Color Padding Removal.
  description: Automatically remove the color padding mask.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: preferences.advanced.useColorTransfer
  label: Color Transfer.
  description: Use a experimental algorithm to recover the original colors of the photo.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: preferences.advanced.imageSize
  label: Image size.
  description: Sets the internal size of the photo that the algorithm will accept. Sizes other than 512x512 can consume more memory and give worse results.
  input: select
  options:
    - label: 256x256
      value: 256
    - label: 512x512
      value: 512
    - label: 768x768
      value: 768
    - label: 1024x1024
      value: 1024
    - label: 1280x1280
      value: 1280

- id: preferences.advanced.compress
  label: Compression level.
  description: High level of compression sacrifices quality for less memory consumption.
  input: select
  options:
    - label: Disabled
      value: 0
    - label: Low
      value: 25
    - label: Medium
      value: 50
    - label: High
      value: 75

- id: preferences.advanced.waifu.enabled
  label: Waifu2X.
  description: Use the algorithm to upscale & denoise the fake nude.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: preferences.advanced.waifu.scale
  label: Upscale ratio.
  description:
  input: select
  options:
    - label: 2x
      value: 2
    - label: 3x
      value: 3
    - label: 4x
      value: 4

- id: preferences.advanced.waifu.denoise
  label: Denoise level.
  description:
  input: select
  options:
    - label: Disabled
      value: 0
    - label: Low
      value: 1
    - label: Medium
      value: 2
    - label: High
      value: 3

- id: preferences.advanced.waifu.tta
  label: TTA level.
  description: Can increase the quality of the upscale but it will take more time.
  input: select
  options:
    - label: Disabled
      value: 0
    - label: Low
      value: 2
    - label: Medium
      value: 4
    - label: High
      value: 8

- id: preferences.advanced.waifu.arch
  label: Model.
  description: Each model can give different results in each photo.
  input: select
  options:
    - label: VGG7
      value: 0
    - label: UpConv7
      value: 1
    - label: ResNet10
      value: 2
    - label: UpResNet10
      value: 3

- id: notifications.run
  label: Every run.
  description: Notify when the program is not in the foreground and a single run have finished.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: notifications.allRuns
  label: Every dream.
  description: Notify when the program is not in the foreground and all the runs have finished.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: notifications.update
  label: Update available.
  description: Notify when there is a new version of DreamTime, DreamPower or the checkpoints.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: folders.cli
  label: DreamPower.
  description: Nudification algorithm.

- id: folders.waifu
  label: Waifu2X.
  description: Upscale and denoise algorithm.

- id: folders.models
  label: Models.
  description: Final nudes.

- id: folders.cropped
  label: Temporal.
  description: Temporary files for processing.

- id: telemetry.bugs
  label: Error report.
  description: Allow to report errors automatically.
  tooltip: |-
    - Operating system.
    - CPU, RAM and GPU.
    - User settings.
    - Console log.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: telemetry.dom
  label: Session tracking.
  description: Allow to send information about how you use the application. (No sensitive information or photos will be sent)
  tooltip: |-
    - Operating system.
    - CPU, RAM and GPU.
    - User settings.
    - Console log.
    - Actions inside the application. (Photos and sensitive information are censored.)
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false
