name: Build Release

on:
  push:
    paths:
      - src/**
      - .github/workflows/**
    branches:
      - release/*
    tags:
      - v*

jobs:
  build:
    name: ${{ matrix.platform }} (${{ matrix.type }})
    runs-on: ${{ matrix.os }}

    # Strategy
    # (variables for multiple platforms)
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        type:
          - installer
          - portable

        include:
          - os: ubuntu-latest # Ubuntu
            platform: ubuntu
            extension: snap
          - os: windows-latest # Windows
            platform: windows
            extension: exe
          - os: macOS-latest # macOS
            platform: macos
            extension: dmg

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}

      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Yarn
        run: npm install -g yarn

      - name: Setup
        working-directory: src/
        run: yarn install --network-timeout 1000000

      - name: Build Installer
        working-directory: src/
        if: matrix.type == 'installer'
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: yarn run build

      - name: Build Portable
        working-directory: src/
        if: matrix.type == 'portable'
        env:
          GITHUB_SHA: ${{ github.sha }}
          BUILD_PORTABLE: true
        run: yarn run build

      - uses: actions/upload-artifact@v2
        with:
          name: dreamtime-${{ matrix.platform }}-${{ matrix.type }}
          path: |
            dist/*.zip
            dist/*.exe
            dist/*.snap
            dist/*.dmg

      - uses: actions/upload-artifact@v2
        with:
          name: dreamtime-${{ matrix.platform }}-${{ matrix.type }}-static
          path: src/dist

      - name: Deploy to Storage
        working-directory: src/
        continue-on-error: true
        timeout-minutes: 20
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
          BUILD_PLATFORM: ${{ matrix.platform }}
          BUILD_EXTENSION: ${{ matrix.extension }}
          DEPLOY_ENCRYPT_KEY: ${{ secrets.DEPLOY_ENCRYPT_KEY }}
          DEPLOY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_GITHUB_OWNER: dreamnettech
          DEPLOY_TEKNIK_TOKEN: ${{ secrets.DEPLOY_TEKNIK_TOKEN }}
          DEPLOY_TEKNIK_OWNER: dreamnet
          DEPLOY_PINATA_KEY: ${{ secrets.DEPLOY_PINATA_KEY }}
          DEPLOY_PINATA_SECRET: ${{ secrets.DEPLOY_PINATA_SECRET }}
          DEPLOY_MEGA_EMAIL: ${{ secrets.DEPLOY_MEGA_EMAIL }}
          DEPLOY_MEGA_PASSWORD: ${{ secrets.DEPLOY_MEGA_PASSWORD }}
          DEPLOY_MEGA_FOLDER: "/Projects/DreamTime/Releases/"
        run: yarn run deploy

      - name: Deploy to Snapcraft
        if: matrix.type == 'installer' && matrix.platform == 'ubuntu'
        working-directory: dist/
        run: snapcraft upload --release=stable *.snap
